modules/ita/controllers/DeliverySmsController.php
<?php

namespace app\modules\ita\controllers;

use app\components\sms_provider\SmsClubXML;
use app\models\AgentsMapping;
use app\models\Contacts;
use app\models\ContactsPhones;
use app\models\Providers;
use app\models\ProvidersCredentials;
use app\models\Segments;
use app\models\SegmentsRelations;
use app\models\SegmentsResultList;
use app\models\SendSms;
use app\models\search\SendSms as SendSmsSearch;
use app\models\SendSmsStatus;
use app\models\Tenants;
use app\models\Translations;
use app\models\User;
use app\modules\ita\controllers\base\BaseController;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use yii\web\Response;


class DeliverySmsController extends BaseController
{
    public function actionIndex()
    {
        /* Set params */
        $search_data = \Yii::$app->request->get('search');

        \Yii::$app->view->params['header'] = [
            'show_search_panel' => true
        ];

        $filterData = array(
            'providers' => Providers::find()->all(),
            'statuses' => SendSms::STATUS,
            'users' => AgentsMapping::find()->joinWith('user')->where(['tenant_id' => Yii::$app->user->identity->tenant->id])->all(),
        );


        return $this->render('index', [
            'filterData' => $filterData,
        ]);
    }

    public function actionCreate()
    {
        $model = new SendSms();
        $lang = Yii::$app->user->identity->tenant->language->iso;
            $providers = Providers::find()->joinWith('credential')
                ->where(['providers_credentials.tenant_id' => Yii::$app->user->identity->tenant->id])
                ->all();

            $segmentsRelations = SegmentsRelations::find()
                ->where(['id_tenant' => Yii::$app->user->identity->tenant->id])
                    ->indexBy('id_segment')
                ->asArray()
                ->all();

            $segments = Segments::find()
                ->where(['in', 'id' , array_column($segmentsRelations, 'id_segment')])
                ->translate($lang)
                ->all();

            if ($model->load(\Yii::$app->request->post()) && $model->validate()) {
                $model->status = SendSms::STATUS_READY;
                $model->tenant_id = Yii::$app->user->identity->tenant->id;
                $model->save();

                \Yii::$app->response->format = Response::FORMAT_JSON;
                return ['model_id' => $model->id];
            }

        return $this->render('create', [
                'segRelations' => $segmentsRelations,
                'providers' => $providers,
                'segments' => $segments,
            ]
        );
    }

    public function actionGetIndex()
    {
        $search = \Yii::$app->request->get('search');
        $meta = \Yii::$app->request->get('pagination');
        $search_data = [];

        if (isset($search)) {
            parse_str($search, $search_data);
        }

        $searchModel = new SendSmsSearch();
        $query = $searchModel->search($search_data);

        $meta['total'] = $query->count();
        if (isset($meta['perpage']) && isset($meta['page'])) {
            $query->limit($meta['perpage'])->offset($meta['perpage'] * ($meta['page'] - 1))->orderBy('created_at');
        }

        $resultData = [];
        foreach ($query->each(30) as $key => $item) {
            $resultData[$key] = $item->toArray();
            $resultData[$key]['createdWithTimeZone'] = $item->created_at_formatted;
            $resultData[$key]['photo'] = $item->created->photo;
            $resultData[$key]['fio'] = $item->created->first_name . ' ' . $item->created->last_name;
        }

        \Yii::$app->response->format = Response::FORMAT_JSON;
        return ['data' => $resultData, 'meta' => $meta];
    }

    public function actionDelIndex()
    {
        $ids = \Yii::$app->request->post('ids');

        $smsAll = SendSms::find()->where(['in', 'id', $ids])->all();
        foreach ($smsAll as $sms) {
            $sms->delete();
        }

        \Yii::$app->response->format = Response::FORMAT_JSON;
        return 1;
    }

    public function actionView($id)
    {
        $model = SendSms::find()
        ->where(['send_sms.id' => $id])
        ->joinWith('provider')
        ->one();

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionGetView()
    {
        $send_sms_id = \Yii::$app->request->get('send_sms_id');
        $meta = \Yii::$app->request->get('pagination');
        $lang = Yii::$app->user->identity->tenant->language->id;

        $deliveredSms = SendSmsStatus::find()
            ->select([
                'CONCAT(contacts.last_name, \' \', contacts.first_name) as fio',
                'contacts_phones.value as phones',
                'send_sms_status.segments',
                'send_sms_status.status',
                'send_sms_status.data',
                'send_sms.segment_copy',
            ])
            ->leftJoin(ContactsPhones::tableName(), "send_sms_status.contact_phone_id = contacts_phones.id")
            ->leftJoin(Contacts::tableName(), "contacts_phones.contact_id = contacts.id")
            ->leftJoin(SendSms::tableName(), "send_sms_status.send_sms_id = send_sms.id")
            ->where(['send_sms_id' => $send_sms_id]);

        $meta['total'] = $deliveredSms->count();
        $deliveredSms->limit($meta['perpage'])->offset($meta['perpage'] * ($meta['page'] - 1))->orderBy('contact_phone_id, send_sms_id DESC');
        $deliveredSms = $deliveredSms->asArray()->all();

        $allSegment = Segments::find()->indexBy('id')->all();
        foreach ($deliveredSms as $key => $sms) {
            $status = array_flip(SendSmsStatus::DELIVERY_STATUS);
            $deliveredSms[$key]['status'] = $status[$sms['status']];
            $segments = [];
            foreach (explode(";", $sms['segments']) as $item) {
                $segments[] = $allSegment[$item]->name;
            }

            $deliveredSms[$key]['segments'] = implode(',', $segments);
            $array_segment_list = json_decode($deliveredSms[$key]['segment_copy'],true);
            $array_segment_sort = [];
            $final_array = [];
            foreach($array_segment_list as $tes) {
                $array_segment_sort[$tes['id_segment']] = $tes['name'];
            }
            foreach(explode(';', $sms['segments']) as $segment_id){
                $final_array[] = $array_segment_sort[$segment_id];
            }
            $deliveredSms[$key]['segment_list_copy'] = $final_array;
        }

        \Yii::$app->response->format = Response::FORMAT_JSON;
        return ['data' => $deliveredSms, 'meta' => $meta];
    }

    /**
     * @param $provider_id
     *
     * @return array
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionGetAlphaName($provider_id)
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;
        if (!$provider_id)
            return [];
        
        $provider = ProvidersCredentials::find()
            ->where(['provider_id' => $provider_id])
            ->andWhere(['tenant_id' => Yii::$app->user->identity->tenant->id])
            ->one();

        if ($provider === null)
            throw new NotFoundHttpException('Provider not found!');

        return ['data' => $provider->getAlphaName()];
    }

    /**
     * @param $id
     *
     * @return \app\models\SendSms
     * @throws \yii\web\NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = SendSms::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/ita/views/delivery-sms/_filters-left.php
<?php
use app\helpers\TranslationHelper;

$lang = Yii::$app->user->identity->tenant->language->iso;
?>
<div class="filter-item">
    <a href="#" class="m-link m--font-bold active" id="all_sms">
        <?= TranslationHelper::getTranslation('all_sended_sms', $lang) ?>
    </a>
</div>
<div class="filter-item">
    <a href="#" class="m-link m--font-bold" id="my_sms">
        <?= TranslationHelper::getTranslation('my_sended_sms', $lang) ?>
    </a>
</div>

modules/ita/views/delivery-sms/_filters-right.php
<?php
use app\helpers\TranslationHelper;
use app\helpers\MCHelper;

$lang = Yii::$app->user->identity->tenant->language->iso;
$search = \Yii::$app->request->get('search');
?>

<div class="row filters-right-search">
    <div class="col-lg-6">
        <div class="m-accordion m-accordion--default" id="m_accordion_1" role="tablist">
            <div class="m-accordion__item">
                <div class="m-accordion__item-head" role="tab" id="m_accordion_1_item_1_head" data-toggle="collapse" href="#m_accordion_1_item_1_body" aria-expanded="true">
                    <span class="m-accordion__item-title m--font-transform-u m--font-bolder">
                        Данные рассылки
                    </span>
                    <span class="m-accordion__item-mode"></span>
                </div>
                    <div class="m-accordion__item-body show" id="m_accordion_1_item_1_body" role="tabpanel" aria-labelledby="m_accordion_1_item_1_head" data-parent="#m_accordion_1">
                        <div class="m-accordion__item-content">
                            <div class="form-group">
                                <input type="text" class="form-control m-input" name="title" placeholder="<?= app\helpers\TranslationHelper::getTranslation('filter_top_placeholder_field_name', $lang, 'Name delivery') ?>">
                            </div>
                            <div class="form-group">
                                <select class="form-control m-select2" id="select_provider" name="select_provider"></select>
                            </div>
                            <div class="form-group">
                                <select class="form-control m-select2" id="select_status" name="select_status"></select>
                            </div>
                            <div class="form-group">
                                <div class="input-group" id="m_daterangepicker_completion">
                                    <?= \yii\helpers\Html::input('hidden', 'date_start') ?>
                                    <?= \yii\helpers\Html::input('hidden', 'date_end') ?>
                                    <input type="text" class="form-control m-input" placeholder="<?= app\helpers\TranslationHelper::getTranslation('filter_top_placeholder_field_date_send', $lang, 'Date send') ?>"/>
                                    <div class="input-group-append">
                                        <span class="input-group-text">
                                            <i class="la la-calendar-check-o"></i>
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <select class="form-control m-select2" id="select_user" name="select_user">
                                    <option value="<?= \Yii::$app->user->id ?>"><?= \Yii::$app->user->identity->last_name ?> <?= \Yii::$app->user->identity->first_name ?></option>
                                </select>
                            </div>
                        </div>
                    </div>

            </div>
        </div>
    </div>
    <div class="col-lg-6">
        
    </div>
</div>

modules/ita/views/delivery-sms/index.php
<?php

use app\helpers\TranslationHelper;
use yii\helpers\Url;

$lang = Yii::$app->user->identity->tenant->language->iso;
?>
<?php
$this->title = TranslationHelper::getTranslation('dess_sms_page_title', $lang, 'Delivering sms');
$this->registerJsFile('@web/js/delivery-sms/index.min.js', ['depends' => \app\assets\MetronicAsset::className()]);
$this->registerJsFile('@web/js/delivery-sms/filter.min.js', ['depends' => \app\assets\MetronicAsset::className()]);
$this->registerCSSFile('@web/css/delivery-sms/index.min.css', ['depends' => \app\assets\MetronicAsset::className()]);
$this->registerJs('var currentUserId = "'.Yii::$app->user->id.'";',\yii\web\View::POS_HEAD);
?>

<?php $this->beginBlock('filters-left') ?>
<?= $this->render('_filters-left'); ?>
<?php $this->endBlock(); ?>

<?php $this->beginBlock('filters-right') ?>
<?= $this->render('_filters-right'); ?>
<?php $this->endBlock(); ?>

<?php
$this->beginBlock('extra_modals');
$this->endBlock();
?>

<div class="m-portlet m-portlet--mobile" id="delivery_sms_datatable_portlet">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                    <?= TranslationHelper::getTranslation('dess_sms_page_title', $lang, 'Sms deliverings') ?>
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <div class="head_tools_left">
                <div id="bulk_dess_sms_buttons" class="hidden">
                    <button id="remove-mess-sms" class="btn btn-sm btn-outline-info" title="<?= TranslationHelper::getTranslation('delete', $lang, 'Delete'); ?>">
                        <i class="la la-trash"></i>
                        <?= TranslationHelper::getTranslation('delete', $lang, 'Delete'); ?>
                    </button>
                </div>
            </div>
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="<?= Url::toRoute(Yii::$app->user->identity->tenant->id . '/delivery-sms/create') ?>" class="btn btn-success m-btn m-btn--icon">
                        <span>
                            <i class="la la-plus-circle"></i>
                            <span>
                                <?= TranslationHelper::getTranslation('dess_sms_add_new_btn', $lang, 'Add delivering'); ?>
                            </span>
                        </span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="m-portlet__body">
        <div class="m_datatable" id="dess_sms_data_table"></div>
    </div>
</div>

modules/ita/views/delivery-sms/view.php
<?php

use app\helpers\TranslationHelper;

$lang = Yii::$app->user->identity->tenant->language->iso;
?>
<?php
$delivery_name = (isset($delivery['name']) && !empty($delivery['name'])) ? (trim($delivery['name'])) : '';
$this->title = TranslationHelper::getTranslation('dess_sms_view_title', $lang, 'Sms delivery') . ' - ' . $delivery_name;
$this->registerJsFile('@web/js/delivery-sms/view.min.js', ['depends' => \app\assets\MetronicAsset::className()]);
$this->registerCSSFile('@web/css/delivery-sms/view.min.css', ['depends' => \app\assets\MetronicAsset::className()]);
$this->registerJs('var send_sms_id = '.$model->id.';', \yii\web\View::POS_HEAD);
?>

<?php
$this->beginBlock('extra_modals');
$this->endBlock();
?>

<div class="m-portlet m-portlet--mobile" id="sms_delivery_stats_portlet">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                    <?= $model->name; ?>
                </h3>
            </div>
        </div>
    </div>
    <?php
        $percentTrue = 0;
        $percentFalse = 0;

        if(isset($model->count_delivered) && isset($model->count_phones) && isset($model->count_not_delivered)) {
            $percentTrue  = ($model->count_delivered * 100) / $model->count_phones;
            $percentFalse = ($model->count_not_delivered * 100) / $model->count_phones;
        }
    ?>
    <div class="m-portlet__body">
        <div class="progress-stats-block mb-4 row">
            <div class="col-12 col-md-6 mb-3 mb-md-0">
                <div class="recipients_count_block mb-4 row">
                    <div class="col-6">
                        <span class="text-nowrap">
                            <span class="count-block font-italic m--font-bolder m--font-brand mr-1"><?= isset($model->count_phones)? $model->count_phones:'';?></span>
                            <span class="word-block font-italic m--font-bold"><?= TranslationHelper::getTranslation('dess_sms_view_recipients_count_label', $lang, 'Recipients') ?></span>
                        </span>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="recipients_count_block mb-4 row">
                    <div class="col-6">
                        <span class="text-nowrap">
                            <span class="word-block font-italic m--font-bold"><?= TranslationHelper::getTranslation('dess_email_delivery_provider_label', $lang, 'Recipients') ?>:</span>
                            <span class="count-block font-italic m--font-bolder m--font-brand mr-1"><?= isset($model->count_phones)? $model->provider['name']:'';?></span>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="progress-stats-block mb-4 row">
            <div class="col-12 col-md-6 mb-3 mb-md-0">
                <div class="d-flex justify-content-between m--font-bolder mb-1">
                    <span><?= TranslationHelper::getTranslation('dess_sms_view_delivery_rate_label', $lang, 'Delivery rate') ?></span>
                    <span class="m--font-brand"><?= isset($percentTrue)? $percentTrue:''?>%</span>
                </div>
                <div class="progress">
                    <div class="progress-bar m--bg-success" role="progressbar" style="width: <?= isset($percentTrue)? $percentTrue:''?>%;" aria-valuenow="<?= isset($percentTrue)? $percentTrue:''?>" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="d-flex justify-content-between m--font-bolder mb-1">
                    <span><?= TranslationHelper::getTranslation('dess_sms_view_error_rate_label', $lang, 'Error rate') ?></span>
                    <span class="m--font-brand"><?= isset($percentFalse)? $percentFalse:''?>%</span>
                </div>
                <div class="progress">
                    <div class="progress-bar m--bg-danger" role="progressbar" style="width: <?= isset($percentFalse)? $percentFalse:''?>%;" aria-valuenow="<?= isset($percentFalse)? $percentFalse:''?>" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
        </div>
        <div style="height: 25px;"></div>
        <div class="row mb-4">
            <div class="col-12">
                <div class="container">
                    <div class="stats-squares row">
                        <div class="stat-item text-center col-12 col-sm-4">
                            <div class="content">
                                <div class="number m--font-success m--font-bolder">
                                    <span><?= isset($model->count_phones)? $model->count_phones:'';?></span>
                                </div>
                                <div class="text m--font-bold">
                                    <span><?= TranslationHelper::getTranslation('dess_sms_view_send_label', $lang, 'Send') ?></span>
                                </div>
                            </div>
                        </div>
                        <div class="stat-item text-center col-12 col-sm-4">
                            <div class="content">
                                <div class="number m--font-info m--font-bolder">
                                    <span><?= isset($model->count_delivered)? $model->count_delivered:'';?></span>
                                </div>
                                <div class="text m--font-bold">
                                    <span><?= TranslationHelper::getTranslation('dess_sms_view_delivery_label', $lang, 'Delivery') ?></span>
                                </div>
                            </div>
                        </div>
                        <div class="stat-item text-center col-12 col-sm-4">
                            <div class="content">
                                <div class="number m--font-danger m--font-bolder">
                                    <span><?= isset($model->count_not_delivered)? $model->count_not_delivered:'';?></span>
                                </div>
                                <div class="text m--font-bold">
                                    <span><?= TranslationHelper::getTranslation('dess_sms_view_error_label', $lang, 'Error') ?></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="recipients_count_block mb-4 row">
            <div class="col-12">
                <span class="text-nowrap">
                    <span class="word-block font-italic m--font-bold"><?= TranslationHelper::getTranslation('dess_sms_text_title', $lang, 'Sms text') ?>:</span>
                    <span class="count-block font-italic m--font-bolder m--font-brand mr-1"><?= isset($model->text)? $model->text:'';?></span>
                </span>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div id="sms-delivery-report-datatable"></div>
            </div>
        </div>
    </div>
</div>